spring:
  mongodb:
    uri: mongodb://localhost:27017/eventcart_catalog_test
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092

eventcart:
  security:
    enabled: false
