package com.eventcart.common.events;

import java.math.BigDecimal;
import java.util.List;

/**
 * Kafka event published after order-service creates an order.
 *
 * <p>This is the first real business event in EventCart. Inventory-service
 * consumes it to reserve stock asynchronously.</p>
 *
 * @param metadata common event metadata used for traceability and versioning
 * @param orderId order ID generated by order-service
 * @param customerId customer that placed the order
 * @param items ordered item snapshots
 * @param totalAmount total amount for the order
 * @param currency currency code used by the order total
 */
public record OrderCreatedEvent(
        EventMetadata metadata,
        String orderId,
        String customerId,
        List<OrderCreatedItem> items,
        BigDecimal totalAmount,
        String currency
) {
    public static final String EVENT_TYPE = "order.created";
    public static final int VERSION = 1;
}
