package com.eventcart.common.events;

import java.math.BigDecimal;

/**
 * Kafka event published when a product is created in the catalog domain.
 *
 * <p>The event is intentionally a product snapshot. Consumers should not need
 * to call the catalog service just to understand the product that was created.
 * Later, this event can be consumed by search, analytics, notification, or
 * cache-refresh services.</p>
 *
 * @param metadata common event metadata used for traceability and versioning
 * @param productId unique product ID generated by the catalog service
 * @param sku business-facing stock keeping unit
 * @param name product display name
 * @param category product category
 * @param price product price at creation time
 * @param currency ISO-style currency code used for the price
 */
public record ProductCreatedEvent(
        EventMetadata metadata,
        String productId,
        String sku,
        String name,
        String category,
        BigDecimal price,
        String currency
) {
    public static final String EVENT_TYPE = "catalog.product.created";
    public static final int VERSION = 1;
}
