apiVersion: v1
kind: ConfigMap
metadata:
  name: eventcart-config
  namespace: eventcart
data:
  EVENTCART_SECURITY_ENABLED: "true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-bootstrap.platform.svc.cluster.local:9092"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://keycloak.example.com/realms/eventcart"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://keycloak.example.com/realms/eventcart/protocol/openid-connect/certs"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
  EVENTCART_CLIENTS_CATALOG_BASE_URL: "http://catalog-service:8081"
  EVENTCART_CLIENTS_CART_BASE_URL: "http://cart-service:8082"
  SPRING_DATA_REDIS_HOST: "redis-master.platform.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
